remote_theme: pmarsceill/just-the-docs
title: "Mega Taxi Docs"
search_enabled: true
aux_links:
  "Issues and Feedback":
    - "//github.com/MegaTaxiApp/megataxi-docs/issues"
aux_links_new_tab: true
heading_anchors: true
permalink: pretty
